# Uncomment the next line to define a global platform for your project
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’

targetsArray = [‘LearnGPUImage’]
# 循环
targetsArray.each do |t|
    target t do
        pod 'GPUImage'
    end

end
